/**
 * Script to sync NEXT_PUBLIC_ environment variables from root .env to frontend/.env.local
 * This ensures Next.js can read the variables at runtime (middleware, etc.)
 */

const fs = require('fs')
const path = require('path')

const rootEnvPath = path.join(__dirname, '..', '..', '.env')
const frontendEnvPath = path.join(__dirname, '..', '.env.local')

// Read root .env file
if (!fs.existsSync(rootEnvPath)) {
  console.warn(`⚠️  Root .env file not found at ${rootEnvPath}`)
  console.warn('   Make sure you have created .env in the project root')
  process.exit(0)
}

const rootEnvContent = fs.readFileSync(rootEnvPath, 'utf8')

// Extract only NEXT_PUBLIC_ variables
const nextPublicVars = rootEnvContent
  .split('\n')
  .filter(line => {
    const trimmed = line.trim()
    return trimmed.startsWith('NEXT_PUBLIC_') && !trimmed.startsWith('#')
  })
  .join('\n')

if (!nextPublicVars.trim()) {
  console.warn('⚠️  No NEXT_PUBLIC_ variables found in root .env')
  process.exit(0)
}

// Write to frontend/.env.local
const envLocalContent = `# Auto-generated from root .env file
# Do not edit this file manually - it will be overwritten
# Edit the root .env file instead

${nextPublicVars}
`

fs.writeFileSync(frontendEnvPath, envLocalContent, 'utf8')
console.log('✅ Synced NEXT_PUBLIC_ variables from root .env to frontend/.env.local')

